/**
 * Quota failure detection, reset-window parsing, and provider-status
 * normalization.
 *
 * Meridian reports an exhausted subscription quota on two paths: an HTTP 429, and
 * an error event inside an otherwise successful SSE stream. Both currently land in
 * retryable classes (`RATE_LIMIT` and `TRANSPORT`), so the harness retries a
 * condition that cannot succeed until a window resets. A dedicated code that is
 * absent from `DEFAULT_RETRY_POLICY.retryableCodes` stops that, and the reset
 * window from the message becomes the retry-after the harness reports.
 *
 * The message is generated by the `agy` CLI and relayed by Meridian rather than
 * constructed by Meridian, so the matcher here is deliberately lenient about
 * wording and strict about requiring both a quota word and an exhausted word. A
 * plain rate-limit 429 has no quota word and keeps its retry.
 *
 * Pure module: no harness imports, so it is unit-testable offline.
 *
 * @module @local/dsh-meridian-antigravity/lib/quota
 */

/**
 * Classification for a failure that will not clear until a quota window resets.
 *
 * This is the harness's own `QUOTA_EXCEEDED_CODE` (`llm/src/error.ts:28`), which
 * this connector already uses for a quota 429. It is deliberately absent from
 * `DEFAULT_RETRY_POLICY.retryableCodes`, so the harness does not retry it — which
 * is the point, because a quota failure cannot succeed until the window resets.
 */
export const QUOTA_FAILURE_CODE = 'QUOTA'

/** The provider id Meridian uses for the Antigravity backend. */
export const ANTIGRAVITY_PROVIDER_ID = 'antigravity'

const QUOTA_WORD = /\bquota\b|allowance|usage limit|\bcredits?\b/i
const EXHAUSTED_WORD = /reach|exceed|exhaust|deplet|out of|no remaining|limit hit/i

/**
 * Whether a provider message describes an exhausted quota.
 *
 * @param text - the provider's message, from a response body or a stream event.
 * @returns true when the text names both a quota and its exhaustion.
 */
export function isQuotaMessage(text) {
  if (typeof text !== 'string' || text.length === 0) return false
  return QUOTA_WORD.test(text) && EXHAUSTED_WORD.test(text)
}

/**
 * Read the reset window out of a quota message.
 *
 * Handles the CLI's compact duration form, as in `Resets in 2h43m43s`, with any
 * subset of the three units. An absent or unparseable window returns `undefined`
 * rather than zero, so a caller never reports "usable now" for an unknown wait.
 *
 * @param text - the provider's message.
 * @returns milliseconds until reset, or undefined when the text does not say.
 */
export function parseResetWindow(text) {
  if (typeof text !== 'string') return undefined
  const match = /resets?\s+in\s+((?:\d+\s*h)?(?:\s*\d+\s*m)?(?:\s*\d+\s*s)?)/i.exec(text)
  if (match === null || match[1].trim().length === 0) return undefined
  const parts = { h: 0, m: 0, s: 0 }
  const unit = /(\d+)\s*([hms])/gi
  let found = false
  let piece
  while ((piece = unit.exec(match[1])) !== null) {
    parts[piece[2].toLowerCase()] = Number(piece[1])
    found = true
  }
  if (!found) return undefined
  const ms = (parts.h * 3600 + parts.m * 60 + parts.s) * 1000
  return ms > 0 ? ms : undefined
}

/**
 * Classify a provider message as a quota failure when it is one.
 *
 * @param text - the provider's message.
 * @returns `{ code, retryAfterMs }` with `retryAfterMs` possibly undefined, or
 *   undefined when the message is not about quota.
 */
export function quotaFailure(text) {
  if (!isQuotaMessage(text)) return undefined
  const retryAfterMs = parseResetWindow(text)
  return { code: QUOTA_FAILURE_CODE, ...retryAfterMs === undefined ? {} : { retryAfterMs } }
}

/** Collapse Meridian's activity block to the fields the strip shows. */
function normalizeActivity(activity) {
  if (activity === null || typeof activity !== 'object') return undefined
  const fields = ['requests', 'errors', 'inputTokens', 'outputTokens', 'cacheReadTokens']
  const out = {}
  for (const field of fields) {
    const value = activity[field]
    if (typeof value === 'number' && Number.isFinite(value)) out[field] = value
  }
  return Object.keys(out).length === 0 ? undefined : out
}

/** First non-empty string among the candidates. */
function firstText(...values) {
  for (const value of values) {
    if (typeof value === 'string' && value.length > 0) return value
  }
  return undefined
}

/**
 * Reduce Meridian's `/providers/status` payload to what the strip renders.
 *
 * The `unavailable` case is first class rather than an edge case: an account
 * whose quota cannot be read reports no windows and carries Meridian's own error,
 * and that has to reach the user intact instead of looking like empty quota.
 *
 * @param payload - the parsed JSON body.
 * @param options - `provider` id to select, and `now` for the timestamp.
 * @returns a stable snapshot: status, optional error, windows, optional activity.
 */
export function normalizeProviderStatus(payload, options = {}) {
  const provider = options.provider ?? ANTIGRAVITY_PROVIDER_ID
  const now = options.now ?? Date.now()
  const providers = Array.isArray(payload?.providers) ? payload.providers : []
  const entry = providers.find(candidate => candidate?.id === provider)

  if (entry === undefined) {
    return {
      status: providers.length === 0 ? 'unavailable' : 'missing',
      error: `Meridian's status response did not include the "${provider}" provider`,
      windows: [],
      fetchedAt: now,
    }
  }

  const windows = []
  const accountError = []
  for (const account of Array.isArray(entry.accounts) ? entry.accounts : []) {
    const accountId = typeof account?.id === 'string' ? account.id : undefined
    if (typeof account?.error === 'string' && account.error.length > 0) accountError.push(account.error)
    for (const window of Array.isArray(account?.windows) ? account.windows : []) {
      const utilization = window?.utilization
      if (typeof utilization !== 'number' || !Number.isFinite(utilization)) continue
      const resetsAt = window?.resetsAt
      windows.push({
        ...accountId === undefined ? {} : { account: accountId },
        type: typeof window?.type === 'string' && window.type.length > 0 ? window.type : 'unknown',
        utilization: Math.min(1, Math.max(0, utilization)),
        ...typeof resetsAt === 'number' && Number.isFinite(resetsAt) ? { resetsAt } : {},
      })
    }
  }

  const error = firstText(entry.error, ...accountError)
  const activity = normalizeActivity(entry.activity)
  return {
    status: windows.length > 0 ? 'ready' : (firstText(entry.status) ?? 'unknown'),
    ...error === undefined ? {} : { error },
    windows,
    ...activity === undefined ? {} : { activity },
    fetchedAt: now,
  }
}
