/**
 * Offline tests for the failure-text classifiers.
 *
 * The module under test imports nothing, so this runs with plain
 * `node --test tests/failure.test.js` and needs no module-resolution rig.
 *
 * Every fixture below is copied verbatim from real failures, so a change in the
 * provider's wording is a test failure rather than a silent misclassification.
 */

import assert from 'node:assert/strict'
import { test } from 'node:test'

import {
  blockedReplyNotice,
  isAgentInterrupted,
  isContentFiltered,
  isSpentBatch,
  rewrittenContinuationNotice,
  spentBatchNotice,
} from '../lib/failure.js'

/** The detail a blocked generation really produced, trimmed only at the tail. */
const CONTENT_FILTER_DETAIL = 'Your previous response was blocked by content safety filters: The model'
  + ' output could not be generated. This output contains sensitive words that violate Google\'s'
  + ' [Generative AI Prohibited Use policy](https://policies.google.com/terms/generative-ai/use-policy).'
  + ' If you think this was an error, [send feedback](https://ai.google.dev/gemini-api/docs/troubleshooting).\n'
  + 'Please provide a response that complies with content policies, or briefly explain to the user why you'
  + ' cannot help with this request\nRetries remaining: 3'

/** The 409 detail for a batch Meridian already consumed. */
const SPENT_BATCH_DETAIL = 'Meridian Antigravity: Antigravity tool result was already consumed; append the'
  + ' subsequent assistant response before continuing'

/** The other, unrecoverable 409: the delivered history genuinely changed. */
const REWRITE_DETAIL = 'Meridian Antigravity: Antigravity tool continuation changed its delivered history'
  + ' or tool batch'

/**
 * Verbatim from an `exchanges` row in Meridian's ledger: the most frequent live
 * failure, and one that used to be invisible inside `SERVER`.
 */
const AGENT_INTERRUPTED_DETAIL = 'the connection to the agent was interrupted before the response finished:'
  + ' subscriber fell behind updates, stalled for 7s'

test('a blocked generation is recognised from the CLI detail', () => {
  assert.equal(isContentFiltered(CONTENT_FILTER_DETAIL), true)
  // The three alternations are independent: any one alone must be enough.
  assert.equal(isContentFiltered('blocked by content safety filters'), true)
  assert.equal(isContentFiltered('violates the Prohibited Use policy'), true)
  assert.equal(isContentFiltered('The model output could not be generated'), true)
})

test('an ordinary cut stream is not a content filter', () => {
  assert.equal(isContentFiltered('server closed the stream before message_stop'), false)
  assert.equal(isContentFiltered('unparseable SSE payload (Unexpected token)'), false)
  assert.equal(isContentFiltered(''), false)
  assert.equal(isContentFiltered(undefined), false)
})

test('a generic "could not be generated" is not claimed as a content filter', () => {
  // The HTTP path feeds whole gateway bodies through this test, so the phrase
  // must name the model output rather than any failed document.
  assert.equal(isContentFiltered('the response could not be generated by the upstream gateway'), false)
  assert.equal(isContentFiltered('a summary could not be generated'), false)
})

test('a dropped agent connection is recognised from the provider detail', () => {
  assert.equal(isAgentInterrupted(AGENT_INTERRUPTED_DETAIL), true)
  assert.equal(isAgentInterrupted('the connection to the agent was interrupted before the response finished'), true)
})

test('related Meridian failures are not mistaken for a dropped agent', () => {
  assert.equal(isAgentInterrupted('Antigravity turn timed out'), false)
  assert.equal(isAgentInterrupted('Request cancelled'), false)
  assert.equal(isAgentInterrupted('status 502'), false)
  assert.equal(isAgentInterrupted(CONTENT_FILTER_DETAIL), false)
  assert.equal(isAgentInterrupted(undefined), false)
})

test('a consumed batch is recognised as spent', () => {
  assert.equal(isSpentBatch(SPENT_BATCH_DETAIL), true)
  assert.equal(isSpentBatch(`Meridian refused this tool continuation... (${SPENT_BATCH_DETAIL})`), true)
})

test('the transcript-rewrite conflict is NOT a spent batch', () => {
  // The two share a 409 and must not share a response: one can be repaired by
  // standing in for a missing reply, the other means the history itself moved.
  assert.equal(isSpentBatch(REWRITE_DETAIL), false)
  assert.equal(isSpentBatch('Meridian Antigravity stream ended before message_stop'), false)
  assert.equal(isSpentBatch(undefined), false)
})

test('the notice names the batch size and reports what happened', () => {
  const notice = spentBatchNotice(3)
  assert.match(notice, /batch of 3 tool results/)
  assert.match(notice, /consumed by a generation the backend blocked and never completed/)
  assert.match(notice, /no reply exists for it/)
  assert.match(notice, /Nothing was lost and no tool ran twice/)
  assert.match(notice, /re-issue your last instruction/i)
})

test('the notice reads correctly for one result and for an unknown count', () => {
  assert.match(spentBatchNotice(1), /batch of 1 tool result /)
  assert.doesNotMatch(spentBatchNotice(1), /1 tool results/)
  for (const unknown of [undefined, 0, -1, 'many']) {
    assert.match(spentBatchNotice(unknown), /This turn's tool batch was consumed/)
  }
})

test('the blocked-reply notice says the text above is what survived', () => {
  const notice = blockedReplyNotice(1)
  assert.match(notice, /^\[Meridian Antigravity\] The batch of 1 tool result /)
  assert.match(notice, /content filter stopped the reply after it had already begun/)
  assert.match(notice, /the text above may be incomplete/)
  assert.match(notice, /no further reply exists for it/)
  assert.match(notice, /Nothing was lost and no tool ran twice/)
  assert.match(notice, /continue from the text above, or re-issue/i)
  // It must not claim no reply exists: a blocked turn can deliver most of one.
  assert.doesNotMatch(notice, /so no reply exists for it/)
})

test('the blocked-reply notice reads correctly for one result and an unknown count', () => {
  assert.match(blockedReplyNotice(2), /batch of 2 tool results/)
  assert.doesNotMatch(blockedReplyNotice(1), /1 tool results/)
  for (const unknown of [undefined, 0, -1, 'many']) {
    assert.match(blockedReplyNotice(unknown), /This turn's tool batch was consumed/)
  }
})

test('the refused-continuation notice names every cause and chooses none', () => {
  // Meridian's 409 covers the delivered history, the tool batch and the model
  // or execution controls, and the connector cannot see which moved. Asserting
  // a rewrite would be a claim it cannot support.
  const notice = rewrittenContinuationNotice(2)
  assert.match(notice, /^\[Meridian Antigravity\] This turn's batch of 2 tool results was delivered/)
  assert.match(notice, /Meridian refused the continuation/)
  assert.match(notice, /no longer matches the request/)
  assert.match(notice, /rewritten after delivery/)
  assert.match(notice, /tool-result pruner/)
  assert.match(notice, /compaction between a tool call and its result/)
  assert.match(notice, /model change applied while a tool batch was open/)
  assert.match(notice, /closes the turn so the conversation can continue/)
  // The claim the notice used to make, and must not make again.
  assert.doesNotMatch(notice, /the transcript changed/)
})

test('the refused-continuation notice reads correctly for one result and an unknown count', () => {
  assert.match(rewrittenContinuationNotice(1), /batch of 1 tool result /)
  assert.doesNotMatch(rewrittenContinuationNotice(1), /1 tool results/)
  for (const unknown of [undefined, 0, -1, 'many']) {
    assert.match(rewrittenContinuationNotice(unknown), /This turn's tool batch was delivered/)
  }
})
